assets/scrambles/two_by_two/222scrambles.json: scripts/raw_scrambles.txt
	python3 scripts/convert_scrambles.py scripts/raw_scrambles.txt
	mv scripts/raw_scrambles_converted.json assets/scrambles/two_by_two/222scrambles.json


