# following page: https://dart.dev/tools/pub/pubspec
name: app
description: "A new Flutter project."
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.12.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  fsrs: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/scrambles/two_by_two/

  # To add custom fonts to your application, add a fonts section here,
  # see https://flutter.dev/to/font-from-package
