@startuml
IdleAndNewScramble : (stop last Stopwatch, show last Solve time) 
IdleAndNewScramble : show all elements. scramble, last solve time 
InspectionUnder15: show countdown hide everyting else
InspectionOver15: show countdown red preceeded by +
HoldStart: still counting down, countdown yellow, count hold time
HoldEnd: get Holdtime, Countdown Time and Start Stopwatch
Solve: Stopwatch

[*] --> IdleAndNewScramble
IdleAndNewScramble --> InspectionUnder15
InspectionUnder15 --> InspectionOver15
InspectionOver15 --> HoldStart
HoldStart --> HoldEnd
HoldEnd --> Solve
Solve --> IdleAndNewScramble
@enduml
